esphome:
  name: alde-proxy
  platform: ESP32
  board: esp32dev
  framework:
    type: arduino
  flash_size: 16MB
  
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  
  ap:
    ssid: "Alde-Proxy Fallback"
    password: "fallback123"

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  # Optional: MQTT-Authentifizierung
  # username: !secret mqtt_username
  # password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

# Enable Home Assistant API
api:
  encryption:
    key: "AxZ09z4S2EJIMxf9X1eF2cV4s8ggxyBEynz8P+LPYLo="
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: "43b6c49d63cd1c9b9c75191b95563641"

logger:
  level: DEBUG

# UART f端r Truma-Modul (Eingang) - LIN1
# GPIO 14/15 (RXD1/TXD1 LIN1)
uart:
  - id: truma_uart
    tx_pin: 15  # TXD1 LIN1
    rx_pin: 14  # RXD1 LIN1
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 2

# UART f端r Alde-Heizung/TIN-Bus (Ausgang) - LIN2
# GPIO 12/13 (TXD2/RXD2 LIN2)
# Wichtig: IO16/17 werden vom Ethernet PHY verwendet!
  - id: alde_uart
    tx_pin: 12  # TXD2 LIN2
    rx_pin: 13  # RXD2 LIN2
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 2

# Optional: CI Bus f端r Dometic Klima (19200 Baud, Master-Modus)
  - id: ci_uart
    tx_pin: 19
    rx_pin: 18
    baud_rate: 19200
    data_bits: 8
    parity: NONE
    stop_bits: 2

# Externe Komponente einbinden
external_components:
  - source:
      type: git
      url: https://github.com/hliebscher/alde2mqtt
      ref: main
    components: [lin_bus_proxy, alde_tin_bus]

# LIN Bus Proxy Komponente
lin_bus_proxy:
  id: proxy
  truma_uart: truma_uart
  alde_uart: alde_uart
  proxy_mode: true
  logging_enabled: true
  log_sensor:
    name: "LIN Bus Proxy Log"
    id: proxy_log

# Sensoren f端r Statistik
sensor:
  - platform: template
    name: "Proxy Truma->Alde Frames"
    id: proxy_truma_alde_count
    unit_of_measurement: "frames"
    accuracy_decimals: 0
    update_interval: 10s
    lambda: |-
      return id(proxy).get_truma_to_alde_count();
      
  - platform: template
    name: "Proxy Alde->Truma Frames"
    id: proxy_alde_truma_count
    unit_of_measurement: "frames"
    accuracy_decimals: 0
    update_interval: 10s
    lambda: |-
      return id(proxy).get_alde_to_truma_count();

# Schalter zum Aktivieren/Deaktivieren des Proxy-Modus
switch:
  - platform: template
    name: "Proxy Modus"
    id: proxy_mode_switch
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    turn_on_action:
      - lambda: |-
          id(proxy).set_proxy_mode(true);
          ESP_LOGI("proxy", "Proxy-Modus aktiviert");
    turn_off_action:
      - lambda: |-
          id(proxy).set_proxy_mode(false);
          ESP_LOGI("proxy", "Proxy-Modus deaktiviert");
          
  - platform: template
    name: "Proxy Logging"
    id: proxy_logging_switch
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    turn_on_action:
      - lambda: |-
          id(proxy).set_logging_enabled(true);
          ESP_LOGI("proxy", "Logging aktiviert");
    turn_off_action:
      - lambda: |-
          id(proxy).set_logging_enabled(false);
          ESP_LOGI("proxy", "Logging deaktiviert");

